### ISSUE TITLE
http.request not handling relative paths

### ISSUE THREAD

**Issue by lukehorvat** [jhiesey/stream-http#16]
If `window.location.href` is `http://localhost:8000/app/#/`, one would expect a GET to `./ping` to be a request to `http://localhost:8000/app/ping`. At least, that's how XMLHttpRequest behaves.

But instead it looks like `http.request` sends the request to `http://localhost:8000./ping`, which is not a valid URL.

**Comment by jhiesey** [comment]
Hm, this is another interesting case where the expectation in the browser is a bit different from the node case. I agree that this should work, but I want to give it a little thought about the right approach, since this case wasn't a consideration when node's `http` api was designed.

For example, relative urls shouldn't work if the host is different! I think rules something like what node's `url.resolve` does, which is itself based on the browser's behavior, would be ideal. I need to give a bit of thought to how to integrate that behavior.

**Comment by jhiesey** [comment]
I have a cleaner fix using `url.resolve`, but it would break IE8 support without this issue being fixed: https://github.com/defunctzombie/node-url/issues/6
