### ISSUE TITLE
Error on Safari 7 in response._onXHRProgress()

### ISSUE THREAD

**Issue by parshap** [jhiesey/stream-http#20]
Sorry, I know this is not very helpful or informative, but I'm seeing an error on Safari 7.

User agent:
```
Mozilla/5.0 (iPad; CPU OS 7_1_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D201 Safari/9537.53
```

Stack trace:
```
TypeError: Type error
  [native code]
  _onXHRProgress@c47a7137e0bd90003fb0f1251f4896981b18d43b.js:2869:2050
  _onXHRProgress@c47a7137e0bd90003fb0f1251f4896981b18d43b.js:2864:3148
  onreadystatechange@c47a7137e0bd90003fb0f1251f4896981b18d43b.js:2864:2748
```

I've narrowed it to `response._onXHRProgress()`, but I don't have any additional context. I'll try to come up with a reproducible test case or at least a non-minified stack trace.

**Comment by jhiesey** [comment]
Could you give me a reproducible example for testing (e.g. a public url and the options you're passing to stream-http)? I can't tell much from this. Since the tests pass in safari 7 and should exercise most of `response._onXHRProgress()` it must be something specific to your circumstances.

I might also be able to guess whats wrong if you can figure out what line of the source those lines/positions in the stack trace correspond to. If you can't figure it out you could also send me your built/minified js and I could take look.

**Comment by parshap** [comment]
Likely fixed in 570f85e according to @jhiesey. See #34 for more info.

**Comment by jhiesey** [comment]
@parshap you beat me to closing this :) I did reproduce the issue and verify that my change fixes it, but it's still possible I only fixed one of multiple underlying causes.

**Comment by parshap** [comment]
:D 

I will keep an eye out for other occurrences. :+1:
