### ISSUE TITLE
ie8

### ISSUE THREAD

**Issue by TrySound** [jhiesey/stream-http#23]
Do we need ie8 support now? If not, you can remove 3 depenendencies.

**Comment by jhiesey** [comment]
Given that other modules used by browserify are no longer supporting ie8 (see https://github.com/defunctzombie/node-url/issues/6), I think this is inevitable at some point.

I see two possibilities:
* Remove all code that can be replaced by global polyfills and tell the user to include the needed ones (like for `Object.keys`, `String.prototype.substr`, etc.), but retain code that can't be replaced by polyfills
* Rip out all code needed for ie8 and make it completely unsupported

Let me ask on irc before making a decision

**Comment by jhiesey** [comment]
Per discussion on irc, we'll keep ie8 support for now. But requiring polyfills will probably come at some point.

**Comment by parshap** [comment]
IRC log for context:

> 1:45:48 PM <jhiesey> substack: what do you think about ie8 support in browerify?
1:46:16 PM <jhiesey> I got this issue on stream-http, which browserify uses as the http shim: https://github.com/jhiesey/stream-http/issues/23
1:55:27 PM <substack> jhiesey: I think if the code is working fine there's no point is breaking it
1:55:58 PM <jhiesey> it's working ok other than adding to the bundle size
1:56:13 PM <jhiesey> but it's also getting increasingly difficult to maintain
1:58:23 PM <jhiesey> substack: i did have to turn off the ie8 tests (even though i know it works) because i keep hitting the unresponsive script dialog in various places
2:00:19 PM <jhiesey> most recently and unavoidably in the event loop turn that runs all of the require()s and initialization code, most of which time isn't spent in my code
2:01:08 PM <parshap> jhiesey: i'd prefer to see ie8 support remain but would be ok with leaving it up to the end-user to include needed global polyfills
2:01:20 PM <jhiesey> ok will keep it for now
2:02:06 PM <parshap> jhiesey: even though we don't officially support IE8, most of our UI (including React) does, and it'd be nice to one day be able to officially support it
2:02:39 PM <parshap> jhiesey: and our "your browser is not supported" page also attempts to make some http calls, so it'd be nice if that continues to work for ie8 users
2:02:54 PM <parshap> (but, honestly, it's not critical)
2:03:01 PM <jhiesey> parshap: that's a good point

**Comment by TrySound** [comment]
@jhiesey We can start with the first possibility.

**Comment by jhiesey** [comment]
Per more discussion, let's do the first option
