### ISSUE TITLE
Consider changing default withCredentials value to false

### ISSUE THREAD

**Issue by cesarandreu** [jhiesey/stream-http#7]
Sending credentials by default increases the risk of leaked credentials. It makes it too easy to shoot yourself in the foot if you don't know any better. Sending sensitive information should be opt-in.

I propose that withCredentials be made an opt-in feature (i.e. set the default to false), forcing the developer to acknowledge the risk involved.

I'm under the impression that browser vendors agree with omitting credentials as the default behavior because that's what GlobalFetch.fetch does.

Thoughts?

**Comment by jhiesey** [comment]
I left the default as true to match browserify's previous `http` implementation, [`http-browserify`](https://github.com/substack/http-browserify/commit/d5965debd0b9066537b51c4405247d086d0fb9d0)

My only concern with changing it is potential compatibility problems with `http-browserify`, but I agree that a default of false would be safer in general. Since cookies are handled differently in node anyway and I doubt there's a lot of code out there specifically designed for `http-browserify` this probably isn't a major concern.

I'll change this tomorrow unless anyone can think of a good reason not to.
